server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/daangn-jangwonik
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: daangn-jangwonik
    password: jangwonik
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
